import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

import { Home } from "../components/Home"

const Page: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Spacetagram</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Home />
    </div>
  )
}

export default Page
